
# available filter modes: EMA(windowed), MA 
Yaw:
  k: 10
  filterMode: 
    mode: EMA 
    alpha: 0.4
  enable: false
Pitch:
  k: 6
  filterMode: 
    mode: EMA
    alpha: 0.4
  gain: 1.5
Roll: 
  k: 6
  filterMode: 
    mode: EMA
    alpha: 0.4
  gain: 1.2
Sway:
  k: 6
  filterMode: 
    mode: EMA 
    # noise: 0.5
    alpha: 0.4
Surge:
  k: 5
  filterMode: 
    # mode: Butter
    # fs: 40
    # cutoff: 10
    # order: 2 
    mode: EMA
    alpha: 0.3
Heave:
  k: 6
  # don't use wiener. heave has a bias from gravity and wiener doesnt work
  filterMode: 
    mode: EMA
    alpha: 0.4
  gain: 0.8
  clampThreshold: 0.5
  DynamicRangeCompressor:
  # TODO: add bias
    bias: 9.81
    threshold: 2
    ratio: 4 
    attack: 0.2
    release: 0.1
    kneeWidth: 0.5

